# Generated by Django 2.2 on 2020-03-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0005_auto_20200305_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachlist',
            name='camp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camps.Camp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachlist',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camps.Coach'),
            preserve_default=False,
        ),
    ]
