# Generated by Django 2.2 on 2020-03-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_auto_20200305_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Camp')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Group')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='SheduleCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Shedule')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chedule_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.SheduleCluster')),
                ('claster_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.ClusterItem')),
            ],
        ),
    ]
