# Generated by Django 2.2 on 2020-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200130_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='news_type',
            field=models.CharField(blank=True, choices=[('N', 'Новости'), ('E', 'Соревнования'), ('C', 'Сборы')], max_length=1, verbose_name='Тип новости'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='post',
            name='news_type',
            field=models.CharField(blank=True, choices=[('N', 'Новости'), ('E', 'Соревнования'), ('C', 'Сборы')], max_length=1, verbose_name='Тип новости'),
        ),
    ]
