# Generated by Django 2.2 on 2020-01-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20200121_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='competitions.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(),
        ),
    ]
