# Generated by Django 2.2 on 2020-01-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20200123_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
