# Generated by Django 2.2 on 2020-01-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20200123_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_id', to='competitions.Event'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='competitions.Category'),
        ),
    ]
