# Generated by Django 2.2 on 2020-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20200123_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='annoncment',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
