# Generated by Django 2.2 on 2020-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_event_annoncment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_protocol',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
