# Generated by Django 2.2 on 2020-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_event_event_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчины/Юноши/Мальчики'), ('F', 'Женщины/Девушки/Девочки'), ('C', 'Пары')], max_length=1),
        ),
    ]
