# Generated by Django 2.2 on 2020-01-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'verbose_name': 'Лагерь', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterField(
            model_name='camp',
            name='date_start',
            field=models.DateField(verbose_name='День начала'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='description',
            field=models.TextField(verbose_name='день окончания'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место'),
        ),
    ]
