# Generated by Django 2.2 on 2020-03-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200304_1957'),
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'verbose_name': 'Лагерь', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterField(
            model_name='camp',
            name='date_start',
            field=models.DateField(verbose_name='День начала'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='description',
            field=models.TextField(verbose_name='день окончания'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_id', to='camps.Camp')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_id', to='general.Photo')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
