# Generated by Django 2.2 on 2020-03-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_camp_albom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Camp')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Coach')),
            ],
        ),
    ]
