# Generated by Django 2.2 on 2020-03-07 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0007_clusteritem_itemincluster_shedule_shedulecluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteritem',
            name='time_end',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='День окончания'),
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='time_start',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='День начала'),
        ),
        migrations.AddField(
            model_name='shedulecluster',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='День окончания'),
        ),
        migrations.AddField(
            model_name='shedulecluster',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='День начала'),
        ),
    ]
